# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blue Sky Tuition
email: hello@blueskytuition.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Bluesky Tuition is a private tuition service run by fully qualified English teachers. Our team of professionals offer quality, individual and personalised English tuition to homes across East London and Essex.    
baseurl: "/blue-sky-tuition" # the subpath of your site, e.g. /blog
twitter_username: blueskytuition
facebook_username: blueskytuition
github_username:  01taylop

# Build settings
markdown: kramdown
highlighter: pygments
